### ISSUE TITLE
Used required module findit has poor support for Windows.

### ISSUE THREAD

**Issue by phun-ky** [mattmcmanus/dox-foundation#23]
```
require('findit').findSync(source)
```

This will only result in returning ONE file in the given `source` directory.. I suggest you find another module for this, or create your own directory walker with fs.readdirSync

**Comment by mattmcmanus** [comment]
I chose findit because of how simple it's api is. I found walkdir to require too much work to do the really simple task I need accomplished here. Personally, I don't really want to throw in too many conditionals to account for windows support as I don't even have a windows machine to test all this on. 

I'm open to suggestions here so please let me know if you know of a library that works.

**Comment by phun-ky** [comment]
Sorry, I forgot to point to relevant issue, https://github.com/substack/node-findit/issues/5

Seems that the module has not been updated for a while

**Comment by soldair** [comment]
hey guys i would love to help with issues you may have with walkdir. 
its api compatible so i dont understand the issues you may have had.... except that follow_symlinks is disabled by default. anyway if you had issues i want to fix them.

``` js
require("walkdir").sync('./',{follow_symlinks:true});
```

**Comment by mattmcmanus** [comment]
Hey @soldair, Sorry about the confusion there. I was thinking of node-walk, not walkdir. If it does the same and works in windows, that is flipp'n awesome. I'll give it a quick test and push it out as soon as I can.

**Comment by soldair** [comment]
cool man. if any windows users report an issue let me know. i'm sorry i
didn't update tests i made the pull quickly before a lunch meeting.

**Comment by mattmcmanus** [comment]
No worries! I took care of it.

**Comment by mattmcmanus** [comment]
Boom! v0.4.3 is out.
